# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_bus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan_data',
            name='itag_mac',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='scan_data',
            name='rpi_mac',
            field=models.CharField(max_length=20),
        ),
    ]
