# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_bus', '0002_auto_20170719_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'verbose_name_plural': 'Buses'},
        ),
        migrations.RenameField(
            model_name='bus',
            old_name='School_name',
            new_name='school_name',
        ),
        migrations.AlterField(
            model_name='driver',
            name='gender',
            field=models.BooleanField(choices=[(True, 'Male'), (False, 'Female')], default=True),
        ),
    ]
