# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_bus', '0003_auto_20170726_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.BooleanField(choices=[(True, 'Male'), (False, 'Female')], default=True),
        ),
    ]
